---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  RDE API Roles & Policies Stack
Parameters:
  KMSKey:
    Description: KMS key to encrypt s3 artifact bucket
    Type: String
    Default: '998de47d-864c-46f2-9a21-48c097978bdb'
  department:
    Type: String
    Default: 'RDEAPI'
  CFNRole:
    Type: String
    Default: 'cfnrole'  
Resources:
  RDEAPICPRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${department}-CP-Role'
      Path: "/"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - codepipeline.amazonaws.com
      Policies:
        - PolicyName: !Sub '${department}-CP-Policy'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: "Allow"
                Action:
                  - 's3:DeleteObject'
                  - 's3:GetBucketLocation'
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:PutObject'
                Resource:
                  - 'arn:aws:s3:::rde-templates'
                  - 'arn:aws:s3:::rde-templates/*'
              - Effect: Allow
                Action:
                  - 'kms:DescribeKey'
                  - 'kms:GenerateDataKey*'
                  - 'kms:Encrypt'
                  - 'kms:ReEncrypt*'
                  - 'kms:Decrypt'
                Resource:
                  - !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KMSKey}'
              - Effect: Allow
                Action:
                  - 'codecommit:ListBranches'
                  - 'codecommit:ListRepositories'
                  - 'codecommit:BatchGetRepositories'
                  - 'codecommit:Get*'
                  - 'codecommit:GitPull'
                  - 'codecommit:UploadArchive'
                Resource:
                  - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:RDE-API'
              - Effect: Allow
                Action:  
                  - 'cloudformation:CreateChangeSet'
                  - 'cloudformation:CreateStack'
                  - 'cloudformation:DeleteStack'
                  - 'cloudformation:Describe*'
                  - 'cloudformation:List*'
                  - 'cloudformation:UpdateStack'
                  - 'cloudformation:ValidateTemplate'
                  - 'cloudformation:ExecuteChangeSet'
                Resource: '*'  
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource:
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/${CFNRole}'
  RDEAPICBRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${department}-CB-Role'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: !Sub '${department}-CB-policy'
          PolicyDocument:
            Version: 2012-10-17
            Statement:        
              - Effect: "Allow"
                Action:
                  - 'ec2:CreateNetworkInterfacePermission'
                  - 'ec2:CreateNetworkInterface'
                  - 'ec2:DeleteNetworkInterface'
                  - 'ec2:DescribeDhcpOptions'
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:DescribeSubnets'
                  - 'ec2:DescribeSecurityGroups'
                  - 'ec2:DescribeVpcs'
                  - 'logs:Describe*'
                  - 'logs:Get*'
                  - 'tag:Get*'
                Resource: '*' #CodeBuild Project Actions      
              - Effect: "Allow"
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:DescribeLogGroups'
                  - 'logs:DescribeLogStreams'
                  - 'logs:PutLogEvents'
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*'
              - Effect: Allow
                Action:
                  - 'kms:DescribeKey'
                  - 'kms:GenerateDataKey*'
                  - 'kms:Encrypt'
                  - 'kms:ReEncrypt*'
                  - 'kms:Decrypt'
                Resource:
                  - !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KMSKey}'    
              - Effect: Allow
                Action:
                  - 's3:DeleteObject'
                  - 's3:GetBucketLocation'
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:PutObject'
                Resource:
                  - 'arn:aws:s3:::rde-templates'
                  - 'arn:aws:s3:::rde-templates/*'
              - Resource: '*'
                Effect: Allow
                Action:            
                  - 'cloudformation:ValidateTemplate'
                  - 'cloudformation:Describe*'
              - Effect: Allow
                Action:
                  - 'ecr:ListImages'
                  - 'ecr:PutImage'
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:InitiateLayerUpload'
                  - 'ecr:UploadLayerPart'
                Resource: '*'
              - Effect: Allow
                Action:
                 - 'dynamodb:GetItem'
                 - 'dynamodb:BatchGetItem'
                 - 'dynamodb:Query'
                 - 'dynamodb:PutItem'
                 - 'dynamodb:UpdateItem'
                 - 'dynamodb:DeleteItem'
                 - 'dynamodb:BatchWriteItem'
                Resource: '*'
  RDEAPICFNRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${department}-CFN-Role'
      Path: "/"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - cloudformation.amazonaws.com
      Policies:
        - PolicyName: !Sub '${department}-CFN-Policy'
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Resource: '*'
                Effect: Allow
                Action:
                  - 's3:*'
                  - 'iam:*'
                  - 'codebuild:*'
                  - 'codepipeline:*'
                  - 'dynamodb:*'
                  - 'elasticloadbalancing:*' 
                  - 'ecs:*'
                  - 'ecr:*'
                  - 'route53:*'
                  - 'logs:*'
                  - 'cloudwatch:*'
                  - 'ec2:*'              
Outputs:
  PipelineRole:
    Description: RDE Security Pipeline Role ARN
    Value: !GetAtt RDEAPICPRole.Arn
    Export:
      Name: !Sub '${department}-pipelinerole'
  BuildRole:
    Description: RDE API  Role ARN
    Value: !GetAtt RDEAPICBRole.Arn
    Export:
      Name: !Sub '${department}-buildrole'
  CFNRole:
    Description: RDE CFN Role ARN
    Value: !GetAtt RDEAPICFNRole.Arn
    Export:
      Name: !Sub '${department}-cfnrole'    
  




